export enum LambdasFunctionNames {
  GetUsers = "GetUsers",
  GetDependencies = "GetDependencies",
  GetTrains = "GetTrains",
  SignUp = "SignUp",
  SignIn = "SignIn",
  SignOut = "SignOut",
  PreSignUp = "PreSignUp",
  VerificationCode = "VerificationCode",
  ResendCode = "ResendCode",
  NotifyTrainLocation = "NotifyTrainLocation",
  CatchTrainCoords = "CatchTrainCoords",
  CreateNewConnection = "CreateNewConnection",
  DeleteConnection = "DeleteConnection",
  NotifyUserOnline = "NotifyUserOnline",
}
