name: deploy-cdk-telemetry-city

permissions:
 id-token: write # Required for GitHub to be able to create a token for you to authenticate with AWS
 contents: read  # Permits your action to read this repo.

on:
  workflow_dispatch:
    inputs:
      stack:
        type: choice
        required: true
        description: Stack service
        options:
          # TODO: Uncomment or add more services as needed.
          - APIGatewayStack
          - lambda-handlers
      selected_env:
        type: choice
        required: true
        description: Deployment Environment
        options:
          #- sbx
          - dev
          - prod
          #- qa

run-name: Deploy ${{ github.event.inputs.stack }} to ${{ github.event.inputs.selected_env }} by ${{ github.triggering_actor }}
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ vars.AWS_SMART_TELEMETRY_CITY_IAM_ROLE }}
          aws-region: ${{ vars.AWS_SMART_TELEMETRY_CITY_REGION }}
          role-session-name: "GitHubActions-DeployLayerStack"

      - name: Bootstrap CDK toolkit
        run: cdk bootstrap aws:/${{vars.AWS_SMART_TELEMETRY_CITY_ACCOUNT}}/${{ vars.AWS_SMART_TELEMETRY_CITY_REGION }}

      - name: Deploy CDK stack ${{ github.event.inputs.stack }}
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'deploy'
          cdk_stack: "${{ github.event.inputs.stack }}"
          cdk_args: '--require-approval never' # This is a toy example, so we don't need to approve changes
          actions_comment: false
