name: deploy-cdk-telemetry-city

permissions:
 id-token: write # Required for GitHub to be able to create a token for you to authenticate with AWS
 contents: read  # Permits your action to read this repo.

on:
  workflow_dispatch:
    inputs:
      stack:
        type: choice
        required: true
        description: Stack service
        options:
          # Add more services as needed.
          - svc-api-gw
          - svc-api-ws
      selected_env:
        type: choice
        required: true
        description: Deployment Environment
        options:
          #- sbx
          - dev
          - prod
          - qa

run-name: Deploy ${{ github.event.inputs.stack }} to ${{ github.event.inputs.selected_env }} by ${{ github.triggering_actor }}

env:
  DEPLOY_ENVIRONMENT: ${{ github.event.inputs.selected_env }}

jobs:
  cdk_deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ vars.AWS_SMART_TELEMETRY_CITY_IAM_ROLE }}
          aws-region: ${{ vars.AWS_SMART_TELEMETRY_CITY_REGION }}
          role-session-name: "GitHubActions-DeployLayerStack"

      - name: install npm
        run: 'sudo apt update -y && sudo apt install nodejs npm -y'

      - name: Install AWS CDK
        run: 'sudo npm install -g aws-cdk'

      - name: Install dependencies
        run: npm install
        working-directory: .

      - name: CDK Synth
        run: cdk synth
        working-directory: .

      - name: CDK bootstrap
        run: cdk bootstrap
        working-directory: .

      - name: CDK Deploy
        run: cdk deploy "${{ github.event.inputs.stack }}" --require-approval never
        working-directory: .
